// <auto-generated />
namespace VidlyV6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBirthDateColumnV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBirthDateColumnV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808151158024_AddBirthDateColumnV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
